/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/jp/Documents/rosWS/custom_ros/src/custom_navigation/msg/M_ADC.msg
 *
 */


#ifndef CUSTOM_NAVIGATION_MESSAGE_M_ADC_H
#define CUSTOM_NAVIGATION_MESSAGE_M_ADC_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace custom_navigation
{
template <class ContainerAllocator>
struct M_ADC_
{
  typedef M_ADC_<ContainerAllocator> Type;

  M_ADC_()
    : header()
    , canal1()
    , canal2()
    , canal3()
    , canal4()
    , canal5()
    , canal6()
    , canal7()
    , canal8()
    , timestamps()  {
    }
  M_ADC_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , canal1(_alloc)
    , canal2(_alloc)
    , canal3(_alloc)
    , canal4(_alloc)
    , canal5(_alloc)
    , canal6(_alloc)
    , canal7(_alloc)
    , canal8(_alloc)
    , timestamps(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _canal1_type;
  _canal1_type canal1;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _canal2_type;
  _canal2_type canal2;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _canal3_type;
  _canal3_type canal3;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _canal4_type;
  _canal4_type canal4;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _canal5_type;
  _canal5_type canal5;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _canal6_type;
  _canal6_type canal6;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _canal7_type;
  _canal7_type canal7;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _canal8_type;
  _canal8_type canal8;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _timestamps_type;
  _timestamps_type timestamps;




  typedef boost::shared_ptr< ::custom_navigation::M_ADC_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_navigation::M_ADC_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct M_ADC_

typedef ::custom_navigation::M_ADC_<std::allocator<void> > M_ADC;

typedef boost::shared_ptr< ::custom_navigation::M_ADC > M_ADCPtr;
typedef boost::shared_ptr< ::custom_navigation::M_ADC const> M_ADCConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_navigation::M_ADC_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_navigation::M_ADC_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/groovy/share/std_msgs/msg'], 'custom_navigation': ['/home/jp/Documents/rosWS/custom_ros/src/custom_navigation/msg'], 'sensor_msgs': ['/opt/ros/groovy/share/sensor_msgs/msg'], 'geometry_msgs': ['/opt/ros/groovy/share/geometry_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_navigation::M_ADC_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_navigation::M_ADC_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_navigation::M_ADC_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_navigation::M_ADC_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_navigation::M_ADC_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_navigation::M_ADC_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_navigation::M_ADC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7e6f37f1d1316025eaaf679de1b998d6";
  }

  static const char* value(const ::custom_navigation::M_ADC_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7e6f37f1d1316025ULL;
  static const uint64_t static_value2 = 0xeaaf679de1b998d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_navigation::M_ADC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_navigation/M_ADC";
  }

  static const char* value(const ::custom_navigation::M_ADC_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_navigation::M_ADC_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float64[] canal1\n\
float64[] canal2\n\
float64[] canal3\n\
float64[] canal4\n\
float64[] canal5\n\
float64[] canal6\n\
float64[] canal7\n\
float64[] canal8\n\
float64[] timestamps\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const ::custom_navigation::M_ADC_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_navigation::M_ADC_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.canal1);
      stream.next(m.canal2);
      stream.next(m.canal3);
      stream.next(m.canal4);
      stream.next(m.canal5);
      stream.next(m.canal6);
      stream.next(m.canal7);
      stream.next(m.canal8);
      stream.next(m.timestamps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct M_ADC_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_navigation::M_ADC_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_navigation::M_ADC_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "canal1[]" << std::endl;
    for (size_t i = 0; i < v.canal1.size(); ++i)
    {
      s << indent << "  canal1[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.canal1[i]);
    }
    s << indent << "canal2[]" << std::endl;
    for (size_t i = 0; i < v.canal2.size(); ++i)
    {
      s << indent << "  canal2[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.canal2[i]);
    }
    s << indent << "canal3[]" << std::endl;
    for (size_t i = 0; i < v.canal3.size(); ++i)
    {
      s << indent << "  canal3[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.canal3[i]);
    }
    s << indent << "canal4[]" << std::endl;
    for (size_t i = 0; i < v.canal4.size(); ++i)
    {
      s << indent << "  canal4[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.canal4[i]);
    }
    s << indent << "canal5[]" << std::endl;
    for (size_t i = 0; i < v.canal5.size(); ++i)
    {
      s << indent << "  canal5[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.canal5[i]);
    }
    s << indent << "canal6[]" << std::endl;
    for (size_t i = 0; i < v.canal6.size(); ++i)
    {
      s << indent << "  canal6[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.canal6[i]);
    }
    s << indent << "canal7[]" << std::endl;
    for (size_t i = 0; i < v.canal7.size(); ++i)
    {
      s << indent << "  canal7[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.canal7[i]);
    }
    s << indent << "canal8[]" << std::endl;
    for (size_t i = 0; i < v.canal8.size(); ++i)
    {
      s << indent << "  canal8[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.canal8[i]);
    }
    s << indent << "timestamps[]" << std::endl;
    for (size_t i = 0; i < v.timestamps.size(); ++i)
    {
      s << indent << "  timestamps[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.timestamps[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_NAVIGATION_MESSAGE_M_ADC_H
