/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/jp/Documents/rosWS/custom_ros/src/custom_navigation/srv/S_ADC.srv
 *
 */


#ifndef CUSTOM_NAVIGATION_MESSAGE_S_ADC_H
#define CUSTOM_NAVIGATION_MESSAGE_S_ADC_H

#include <ros/service_traits.h>


#include <custom_navigation/S_ADCRequest.h>
#include <custom_navigation/S_ADCResponse.h>


namespace custom_navigation
{

struct S_ADC
{

typedef S_ADCRequest Request;
typedef S_ADCResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct S_ADC
} // namespace custom_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::custom_navigation::S_ADC > {
  static const char* value()
  {
    return "6de67c1a66aa444be3767d62a6a225da";
  }

  static const char* value(const ::custom_navigation::S_ADC&) { return value(); }
};

template<>
struct DataType< ::custom_navigation::S_ADC > {
  static const char* value()
  {
    return "custom_navigation/S_ADC";
  }

  static const char* value(const ::custom_navigation::S_ADC&) { return value(); }
};


// service_traits::MD5Sum< ::custom_navigation::S_ADCRequest> should match 
// service_traits::MD5Sum< ::custom_navigation::S_ADC > 
template<>
struct MD5Sum< ::custom_navigation::S_ADCRequest>
{
  static const char* value()
  {
    return MD5Sum< ::custom_navigation::S_ADC >::value();
  }
  static const char* value(const ::custom_navigation::S_ADCRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_navigation::S_ADCRequest> should match 
// service_traits::DataType< ::custom_navigation::S_ADC > 
template<>
struct DataType< ::custom_navigation::S_ADCRequest>
{
  static const char* value()
  {
    return DataType< ::custom_navigation::S_ADC >::value();
  }
  static const char* value(const ::custom_navigation::S_ADCRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::custom_navigation::S_ADCResponse> should match 
// service_traits::MD5Sum< ::custom_navigation::S_ADC > 
template<>
struct MD5Sum< ::custom_navigation::S_ADCResponse>
{
  static const char* value()
  {
    return MD5Sum< ::custom_navigation::S_ADC >::value();
  }
  static const char* value(const ::custom_navigation::S_ADCResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::custom_navigation::S_ADCResponse> should match 
// service_traits::DataType< ::custom_navigation::S_ADC > 
template<>
struct DataType< ::custom_navigation::S_ADCResponse>
{
  static const char* value()
  {
    return DataType< ::custom_navigation::S_ADC >::value();
  }
  static const char* value(const ::custom_navigation::S_ADCResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CUSTOM_NAVIGATION_MESSAGE_S_ADC_H
