/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/turtlebot/Documents/rosWS/custom_ros/src/custom_navigation/srv/S_ADC.srv
 *
 */


#ifndef CUSTOM_NAVIGATION_MESSAGE_S_ADCREQUEST_H
#define CUSTOM_NAVIGATION_MESSAGE_S_ADCREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_navigation
{
template <class ContainerAllocator>
struct S_ADCRequest_
{
  typedef S_ADCRequest_<ContainerAllocator> Type;

  S_ADCRequest_()
    : subscribe(false)
    , adcChannels()
    , adcFreqAcq(0)
    , adcFreqPoll(0)
    , adcBufferSize(0)  {
      adcChannels.assign(false);
  }
  S_ADCRequest_(const ContainerAllocator& _alloc)
    : subscribe(false)
    , adcChannels()
    , adcFreqAcq(0)
    , adcFreqPoll(0)
    , adcBufferSize(0)  {
      adcChannels.assign(false);
  }



   typedef uint8_t _subscribe_type;
  _subscribe_type subscribe;

   typedef boost::array<uint8_t, 8>  _adcChannels_type;
  _adcChannels_type adcChannels;

   typedef uint16_t _adcFreqAcq_type;
  _adcFreqAcq_type adcFreqAcq;

   typedef uint16_t _adcFreqPoll_type;
  _adcFreqPoll_type adcFreqPoll;

   typedef uint32_t _adcBufferSize_type;
  _adcBufferSize_type adcBufferSize;




  typedef boost::shared_ptr< ::custom_navigation::S_ADCRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_navigation::S_ADCRequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct S_ADCRequest_

typedef ::custom_navigation::S_ADCRequest_<std::allocator<void> > S_ADCRequest;

typedef boost::shared_ptr< ::custom_navigation::S_ADCRequest > S_ADCRequestPtr;
typedef boost::shared_ptr< ::custom_navigation::S_ADCRequest const> S_ADCRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_navigation::S_ADCRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_navigation::S_ADCRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/groovy/share/std_msgs/msg'], 'custom_navigation': ['/home/turtlebot/Documents/rosWS/custom_ros/src/custom_navigation/msg'], 'sensor_msgs': ['/opt/ros/groovy/share/sensor_msgs/msg'], 'geometry_msgs': ['/opt/ros/groovy/share/geometry_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_navigation::S_ADCRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_navigation::S_ADCRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_navigation::S_ADCRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_navigation::S_ADCRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_navigation::S_ADCRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_navigation::S_ADCRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_navigation::S_ADCRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9a5b02b00f10349a8178e70cea30327c";
  }

  static const char* value(const ::custom_navigation::S_ADCRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9a5b02b00f10349aULL;
  static const uint64_t static_value2 = 0x8178e70cea30327cULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_navigation::S_ADCRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_navigation/S_ADCRequest";
  }

  static const char* value(const ::custom_navigation::S_ADCRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_navigation::S_ADCRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool subscribe\n\
bool[8] adcChannels\n\
uint16 adcFreqAcq\n\
uint16 adcFreqPoll\n\
uint32 adcBufferSize\n\
\n\
";
  }

  static const char* value(const ::custom_navigation::S_ADCRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_navigation::S_ADCRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.subscribe);
      stream.next(m.adcChannels);
      stream.next(m.adcFreqAcq);
      stream.next(m.adcFreqPoll);
      stream.next(m.adcBufferSize);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct S_ADCRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_navigation::S_ADCRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_navigation::S_ADCRequest_<ContainerAllocator>& v)
  {
    s << indent << "subscribe: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.subscribe);
    s << indent << "adcChannels[]" << std::endl;
    for (size_t i = 0; i < v.adcChannels.size(); ++i)
    {
      s << indent << "  adcChannels[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.adcChannels[i]);
    }
    s << indent << "adcFreqAcq: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.adcFreqAcq);
    s << indent << "adcFreqPoll: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.adcFreqPoll);
    s << indent << "adcBufferSize: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.adcBufferSize);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_NAVIGATION_MESSAGE_S_ADCREQUEST_H
