/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/turtlebot/Documents/rosWS/custom_ros/src/custom_navigation/srv/S_DigitalOut.srv
 *
 */


#ifndef CUSTOM_NAVIGATION_MESSAGE_S_DIGITALOUTREQUEST_H
#define CUSTOM_NAVIGATION_MESSAGE_S_DIGITALOUTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace custom_navigation
{
template <class ContainerAllocator>
struct S_DigitalOutRequest_
{
  typedef S_DigitalOutRequest_<ContainerAllocator> Type;

  S_DigitalOutRequest_()
    : outputState()  {
      outputState.assign(false);
  }
  S_DigitalOutRequest_(const ContainerAllocator& _alloc)
    : outputState()  {
      outputState.assign(false);
  }



   typedef boost::array<uint8_t, 4>  _outputState_type;
  _outputState_type outputState;




  typedef boost::shared_ptr< ::custom_navigation::S_DigitalOutRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::custom_navigation::S_DigitalOutRequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct S_DigitalOutRequest_

typedef ::custom_navigation::S_DigitalOutRequest_<std::allocator<void> > S_DigitalOutRequest;

typedef boost::shared_ptr< ::custom_navigation::S_DigitalOutRequest > S_DigitalOutRequestPtr;
typedef boost::shared_ptr< ::custom_navigation::S_DigitalOutRequest const> S_DigitalOutRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::custom_navigation::S_DigitalOutRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::custom_navigation::S_DigitalOutRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace custom_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/groovy/share/std_msgs/msg'], 'custom_navigation': ['/home/turtlebot/Documents/rosWS/custom_ros/src/custom_navigation/msg'], 'sensor_msgs': ['/opt/ros/groovy/share/sensor_msgs/msg'], 'geometry_msgs': ['/opt/ros/groovy/share/geometry_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::custom_navigation::S_DigitalOutRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::custom_navigation::S_DigitalOutRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_navigation::S_DigitalOutRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::custom_navigation::S_DigitalOutRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_navigation::S_DigitalOutRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::custom_navigation::S_DigitalOutRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::custom_navigation::S_DigitalOutRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "296499f8572b029d54dd751c3721f6e7";
  }

  static const char* value(const ::custom_navigation::S_DigitalOutRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x296499f8572b029dULL;
  static const uint64_t static_value2 = 0x54dd751c3721f6e7ULL;
};

template<class ContainerAllocator>
struct DataType< ::custom_navigation::S_DigitalOutRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "custom_navigation/S_DigitalOutRequest";
  }

  static const char* value(const ::custom_navigation::S_DigitalOutRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::custom_navigation::S_DigitalOutRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool[4] outputState\n\
\n\
";
  }

  static const char* value(const ::custom_navigation::S_DigitalOutRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::custom_navigation::S_DigitalOutRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.outputState);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct S_DigitalOutRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::custom_navigation::S_DigitalOutRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::custom_navigation::S_DigitalOutRequest_<ContainerAllocator>& v)
  {
    s << indent << "outputState[]" << std::endl;
    for (size_t i = 0; i < v.outputState.size(); ++i)
    {
      s << indent << "  outputState[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.outputState[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CUSTOM_NAVIGATION_MESSAGE_S_DIGITALOUTREQUEST_H
